set_property IOSTANDARD LVCMOS18 [get_ports {display_o[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {display_o[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {display_o[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {display_o[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {display_o[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {display_o[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {display_o[0]}]
set_property PACKAGE_PIN W7 [get_ports {display_o[6]}]
set_property PACKAGE_PIN W6 [get_ports {display_o[5]}]
set_property PACKAGE_PIN U8 [get_ports {display_o[4]}]
set_property PACKAGE_PIN V8 [get_ports {display_o[3]}]
set_property PACKAGE_PIN U5 [get_ports {display_o[2]}]
set_property PACKAGE_PIN V5 [get_ports {display_o[1]}]
set_property PACKAGE_PIN U7 [get_ports {display_o[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports AN0]
set_property IOSTANDARD LVCMOS18 [get_ports AN1]
set_property IOSTANDARD LVCMOS18 [get_ports arst]
set_property IOSTANDARD LVCMOS18 [get_ports clk]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property PACKAGE_PIN W19 [get_ports arst]
set_property PACKAGE_PIN U4 [get_ports AN1]
set_property PACKAGE_PIN U2 [get_ports AN0]

set_property IOSTANDARD LVCMOS18 [get_ports AN2]
set_property IOSTANDARD LVCMOS18 [get_ports AN2_in]
set_property IOSTANDARD LVCMOS18 [get_ports AN3]
set_property IOSTANDARD LVCMOS18 [get_ports AN3_in]
set_property PACKAGE_PIN V4 [get_ports AN2]
set_property PACKAGE_PIN W4 [get_ports AN3]
set_property PACKAGE_PIN V17 [get_ports AN2_in]
set_property PACKAGE_PIN V16 [get_ports AN3_in]

create_clock -period 10.000 -name main_clock [get_ports clk]